### ISSUE TITLE
Typo in function name

### ISSUE THREAD

**Issue by vlmutolo** [frjnn/bhtsne#1]
First, thanks so much for providing this crate! I've thought about implementing t-SNE in Rust before, but never took on the challenge. Kudos!

I think you have a typo in one of your function names; `bhtsne::wite_csv` should probably be `write_csv`. Just wanted to let you know.

Thanks, again!

**Comment by frjnn** [comment]
Yes, I know, there a lot of improvement and tweaks that must be done. I'm
currently very busy with uni stuff, however I'm glad to know someone
appreciates my work.

Farewell

**Comment by frjnn** [comment]
Fixed
